-- MySQL Script generated by MySQL Workbench
-- 06/01/17 23:51:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema seguimientoegresados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `carrera`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `carrera` ;

CREATE TABLE IF NOT EXISTS `carrera` (
  `id_carrera` INT(11) NOT NULL COMMENT '',
  `nom_carrera` VARCHAR(15) NOT NULL COMMENT '',
  PRIMARY KEY (`id_carrera`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sectorempresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sectorempresa` ;

CREATE TABLE IF NOT EXISTS `sectorempresa` (
  `id_sector` INT(11) NOT NULL COMMENT '',
  `nom_sector` VARCHAR(8) NOT NULL COMMENT '',
  PRIMARY KEY (`id_sector`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sizeorganitation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sizeorganitation` ;

CREATE TABLE IF NOT EXISTS `sizeorganitation` (
  `id_tamano` INT(11) NOT NULL COMMENT '',
  `nom_tamano` VARCHAR(10) NOT NULL COMMENT '',
  PRIMARY KEY (`id_tamano`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datosalumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datosalumnos` ;

CREATE TABLE IF NOT EXISTS `datosalumnos` (
  `SE_noControl` VARCHAR(8) NOT NULL COMMENT '',
  `SE_carrera` INT(1) NOT NULL COMMENT '',
  `SE_nombre` VARCHAR(50) NOT NULL COMMENT '',
  `SE_direccion` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `SE_telefono` INT(12) NULL DEFAULT NULL COMMENT '',
  `SE_telMovil` INT(12) NULL COMMENT '',
  `SE_email` VARCHAR(30) NULL DEFAULT NULL COMMENT '',
  `SE_pEgreso` VARCHAR(30) NULL DEFAULT NULL COMMENT '',
  `SE_generacion` VARCHAR(9) NOT NULL COMMENT '',
  `SE_estudia` VARCHAR(2) NULL DEFAULT NULL COMMENT '',
  `SE_estudioActual` VARCHAR(50) NULL DEFAULT NULL COMMENT '',
  `SE_empresaTrabajo` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `SE_trabajoEspecialidad` VARCHAR(2) NULL DEFAULT NULL COMMENT '',
  `SE_sectorTrabajo` INT(1) NULL DEFAULT NULL COMMENT '',
  `SE_puestoTrabajo` VARCHAR(40) NULL DEFAULT NULL COMMENT '',
  `SE_tamanoEmpresa` INT(1) NULL DEFAULT NULL COMMENT '',
  `SE_pass` VARCHAR(10) NOT NULL COMMENT '',
  `SE_sexo` VARCHAR(10) NULL COMMENT '',
  PRIMARY KEY (`SE_noControl`)  COMMENT '',
  INDEX `SE_sectorTrabajo_idx` (`SE_sectorTrabajo` ASC)  COMMENT '',
  INDEX `SE_tamanoEmpresa_idx` (`SE_tamanoEmpresa` ASC)  COMMENT '',
  INDEX `SE_carrera_idx` (`SE_carrera` ASC)  COMMENT '',
  CONSTRAINT `SE_carrera`
    FOREIGN KEY (`SE_carrera`)
    REFERENCES `carrera` (`id_carrera`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SE_sectorTrabajo`
    FOREIGN KEY (`SE_sectorTrabajo`)
    REFERENCES `sectorempresa` (`id_sector`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `SE_tamanoEmpresa`
    FOREIGN KEY (`SE_tamanoEmpresa`)
    REFERENCES `sizeorganitation` (`id_tamano`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `preguntasencuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `preguntasencuesta` ;

CREATE TABLE IF NOT EXISTS `preguntasencuesta` (
  `idpreguntasEncuesta` INT(2) NOT NULL COMMENT '',
  `pregunta` VARCHAR(400) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idpreguntasEncuesta`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `puestoempresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `puestoempresa` ;

CREATE TABLE IF NOT EXISTS `puestoempresa` (
  `id_puesto` INT(11) NOT NULL COMMENT '',
  `nom_puesto` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`id_puesto`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `respuestasencuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `respuestasencuesta` ;

CREATE TABLE IF NOT EXISTS `respuestasencuesta` (
  `idRespuestas` INT(2) NOT NULL COMMENT '',
  `respuesta` INT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`idRespuestas`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `datosEncuesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `datosEncuesta` ;

CREATE TABLE IF NOT EXISTS `datosEncuesta` (
  `iddatosEncuesta` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `pre1` INT(1) NOT NULL COMMENT '',
  `pre2` INT(1) NOT NULL COMMENT '',
  `pre3` INT(1) NOT NULL COMMENT '',
  `pre4` INT(1) NOT NULL COMMENT '',
  `pre5` INT(1) NOT NULL COMMENT '',
  `pre6` INT(1) NOT NULL COMMENT '',
  `pre7` INT(1) NOT NULL COMMENT '',
  `pre8` INT(1) NOT NULL COMMENT '',
  `pre9` INT(1) NOT NULL COMMENT '',
  `pre10` INT(1) NOT NULL COMMENT '',
  `pre11` INT(1) NOT NULL COMMENT '',
  `pre12` INT(1) NOT NULL COMMENT '',
  `pre13` INT(1) NOT NULL COMMENT '',
  `pre14` INT(1) NOT NULL COMMENT '',
  `SE_noControl` VARCHAR(8) NULL COMMENT '',
  PRIMARY KEY (`iddatosEncuesta`)  COMMENT '',
  UNIQUE INDEX `SE_noControl_UNIQUE` (`SE_noControl` ASC)  COMMENT '',
  CONSTRAINT `SE_noControl`
    FOREIGN KEY (`SE_noControl`)
    REFERENCES `datosalumnos` (`SE_noControl`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


-- -----------------------------------------------------
-- Table `temporal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `temporal` ;

CREATE TABLE IF NOT EXISTS `temporal` (
  `IdTemporal` INT(3) NOT NULL AUTO_INCREMENT COMMENT '',
  `T_noControl` VARCHAR(8) NOT NULL COMMENT '',
  `T_Nombre` VARCHAR(50) NOT NULL COMMENT '',
  `T_pass` VARCHAR(10) NOT NULL COMMENT '',
  `T_telefono` VARCHAR(12) NULL COMMENT '',
  `T_celular` VARCHAR(12) NULL COMMENT '',
  `T_sexo` VARCHAR(9) NOT NULL COMMENT '',
  PRIMARY KEY (`IdTemporal`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
